version: "2"

services:
  rhino-data-service:
    image: rhino-data-volume:0.1.0
    container_name: rhino-data-service
    volumes:
    - rhino-grafana-volume:/grafana-data
    - rhino-influxdb-volume:/influxdb-data
    command: tail -F /var/log/syslog

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    depends_on:
      - rhino-data-service
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - rhino-influxdb-volume:/var/lib/influxdb

  grafana:
    image: bagdemir/rhino-grafana:1.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - rhino-data-service
    volumes:
      - rhino-grafana-volume:/var/lib/grafana
    links:
      - influxdb

volumes:
  rhino-grafana-volume:
  rhino-influxdb-volume: